# Generated by Django 2.2.6 on 2019-10-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_auto_20191029_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
